### ISSUE TITLE
An error "dist_matrix[i,niche_of_individuals[i]] :invalid subscript type 'list'"

### ISSUE THREAD

**Issue by chenhcsir** [benitezfj/nsga3r#13]
I got the error "dist_matrix[i,niche_of_individuals[i]] :invalid subscript type 'list'" when running my code using "NSGA-III" mode. And I find the problem may occured in the file "associate.R".
By constructing a simple fitness func:

clu_par_op <- function (x,...){
  x=matrix(x,1)
  clu_res = cbind(x[,1],x[,2],sum(x))
  return(clu_res)
}

result <- rmoo(fitness = clu_par_op,
               type = "real-valued",
               strategy = "NSGA-III",
               nObj = 3,
               lower = c(0,0),
               upper = c(1,1),
               monitor = FALSE,
               summary = FALSE,
               popSize = 80,
               # reference_dirs = ref_p,
               n_partitions = 12,
               maxiter = 100)

May I ask how to deal with it?

**Comment by benitezfj** [comment]
I guest you are using a depricated version of the `rmoo` package, as I see you are using the `n_partitions` argument. I tried to replicate the error, but the code runs without any issues:

```
R> clu_par_op <- function (x,...) {
                  x=matrix(x,1)
                  clu_res = cbind(x[,1],x[,2],sum(x))
                  return(clu_res)
     }

R> ref_p <- rmoo::generate_reference_points(3, 12)

R> result <- rmoo::rmoo(fitness = clu_par_op,
               type = "real-valued",
               strategy = "NSGA-III",
               nObj = 3,
               lower = c(0, 0),
               upper = c(1, 1),
               monitor = FALSE,
               summary = FALSE,
               popSize = 80,
               reference_dirs = ref_p,
               maxiter = 100,
               seed = 45)

R> > head(result@fitness)
     [,1]         [,2]         [,3]
[1,]    0 6.711105e-05 6.711105e-05
[2,]    0 6.711105e-05 6.711105e-05
[3,]    0 6.711105e-05 6.711105e-05
[4,]    0 6.711105e-05 6.711105e-05
[5,]    0 6.711105e-05 6.711105e-05
[6,]    0 6.711105e-05 6.711105e-05
```
I modified the code slightly to adapt it to the latest version of `rmoo`. 

Could you try updating the package to the most recent version available on this repository to see if the error persists?

Regards.

**Comment by chenhcsir** [comment]
Thank you for your reply.I'm using the latest version 'rmoo-0.2.0'. I try to debug the code you've modified, but there's the same error. The error message running in the 'Terminal' is as follows:

Package 'rmoo' version 0.2.0
Error in dist_matrix[i, niche_of_individuals[i]] :
  invalid subscript type 'list'
Calls: <Anonymous> ... getAlgorithm -> do.call -> <Anonymous> -> associate_to_niches
Execution halted

I also changed the R version from 4.3.2 to 4.4.2, but it's useless. Is it possible that other dependent packages are needed?

###########################################################################################

I modified the source code 'niche_of_individuals[**]' to 'unlist(niche_of_individuals)[**]', it seems useful. But then I encountered an infinite loop in 'niching.R'. The 'n_remaining - length(survivors)' and 'unlist(niche_of_individuals)' are printed as follow:

[1] 5
[1] 51 21 42 32 72 42 66 21 72

[1] 4
[1] 51 21 42 32 72 42 66 21 72

[1] 3
[1] 51 21 42 32 72 42 66 21 72

[1] 2
[1] 51 21 42 32 72 42 66 21 72

[1] 6
 [1] 71 71  8 72 31 31  8  8  8 71 71  8 72  8

[1] 5
 [1] 71 71  8 72 31 31  8  8  8 71 71  8 72  8

[1] 3
 [1] 71 71  8 72 31 31  8  8  8 71 71  8 72  8

[1] 2
 [1] 71 71  8 72 31 31  8  8  8 71 71  8 72  8

[1] 1
 [1] 71 71  8 72 31 31  8  8  8 71 71  8 72  8

[1] 4
[1] 77  8  8 41  8

[1] 4
[1] 77  8  8 41  8

[1] 2
[1] 77  8  8 41  8

[1] 1
[1] 77  8  8 41  8

[1] 80
  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [26] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [51] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [76] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[101] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[126] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
....(infinite loop)

**Comment by benitezfj** [comment]
Hello,

It is unlikely to be a dependency error, as each `rmoo` version installs/updates the required packages to the necessary versions during installation. I see that you are using version 0.2.0 of `rmoo`. We have made updates to the code, correcting bugs and optimizing processes; the current development version is 0.3.0, which has not yet been released on CRAN.

Could you install this version and test the code again? You can update the package by running:

`devtools::install_github("Evolutionary-Optimization-Laboratory/rmoo")`

Please ensure that the updated version is 0.3.0 before running the tests.

Best regards.

**Comment by chenhcsir** [comment]
Appreciate, the issue has been resolved.
